query tenantList (
  $offset: Int!,
  $limit: Int!
) {
  tenants (
    where: {status: {_eq: "active"}},
    order_by: {name: asc},
    limit: $limit,
    offset: $offset
  ) {
    id
    name
    short_name
    max_points_per_show
    created_at
  }
}
