query tenentSearch (
  $search: String!,
  $offset: Int!,
  $limit: Int!
) {
  tenants (
    where: {_and: [
      {name: {_ilike: $search}},
      {status: {_eq: "active"}}
    ]},
    order_by: {name: asc},
    limit: $limit,
    offset: $offset
  ) {
    id
    name
    created_at
  }
}
