query showFind ($id: Int!) {
  shows_by_pk(id: $id) {
    id
    name
    occurred_at
    volunteer_shows {
      points
      volunteer {
        id
        first_name
        last_name
        positions (where: {show_id: {_eq: $id}}) {
          points
          job {
            id
            name
            points
          }
        }
        awards (
          order_by: {level: {points: desc}},
          limit: 1
        ) {
          awarded_at
          level {
            name
            color
          }
        }
      }
    }
  }
}
