query showFind ($id: Int!) {
  shows_by_pk(id: $id) {
    id
    name
    occurred_at
    volunteer_shows {
      points
      volunteer {
        id
        first_name
        last_name
        positions (where: {show_id: {_eq: $id}}) {
          points
          job {
            id
            name
            points
          }
        }
        enrollees (where: {enrollment: {_and: [
          {start_date: {_lte: "now"}},
          {end_date: {_gte: "now"}},
          {membership: {deleted_at: {_is_null: true}}}
        ]}}) {
          enrollment {
            membership {
              name
            }
          }
        }
        awards (
          order_by: {level: {points: desc}},
          limit: 1
        ) {
          awarded_at
          level {
            name
            color
          }
        }
      }
    }
  }
}
