mutation showInsert (
  $tenant_id: Int!,
  $name: String!,
  $occurred_at: date!,
  $editor_id: Int
) {
  insert_shows(
    objects: {
      name: $name,
      occurred_at: $occurred_at,
      editor_id: $editor_id,
      tenant_id: $tenant_id
    },
  ) {
    returning {
      id
    }
  }
}
