mutation updateShow (
  $id: Int!,
  $name: String!,
  $occurred_at: date!,
  $editor_id: Int
) {
  update_shows(
    where: {id: {_eq: $id}},
    _set: {
      name: $name,
      occurred_at: $occurred_at,
      editor_id: $editor_id
    },
  ) {
    returning {
      id
    }
  }
}
