query jobActiveList (
  $tenant_id: Int!
) {
  jobs (
    where: {_and: [
      {deleted_at: {_is_null: true}},
      {tenant_id: {_eq: $tenant_id}}
    ]},
    order_by: {name: asc}
  ) {
    id
    name
    points
  }
}
