mutation jobInsert (
  $tenant_id: Int!,
  $name: String!,
  $points: Int!,
  $editor_id: Int
) {
  insert_jobs(
    objects: {
      name: $name,
      points: $points,
      editor_id: $editor_id,
      tenant_id: $tenant_id
    },
  ) {
    returning {
      id
    }
  }
}
