query jobList (
  $tenant_id: Int!,
  $offset: Int!,
  $limit: Int!
) {
  jobs(
    where: {_and: [
      {deleted_at: {_is_null: true}},
      {tenant_id: {_eq: $tenant_id}}
    ]},
    order_by: {name: asc},
    limit: $limit,
    offset: $offset
  ) {
    id
    name
    points
  }
}
