query jobSearchList (
  $tenant_id: Int!,
  $offset: Int!,
  $limit: Int!,
  $search: String!
) {
  jobs(
    where: {_and: [
      {name: {_ilike: $search}},
      {tenant_id: {_eq: $tenant_id}}
    ]},
    order_by: {name: asc},
    limit: $limit,
    offset: $offset
  ) {
    id
    name
    points
    positions_aggregate (distinct_on: volunteer_id) {
      aggregate {
        count
      }
    }
  }
}
