mutation jobUpdate (
  $id: Int!,
  $name: String!,
  $points: Int!,
  $editor_id: Int
) {
  update_jobs(
    where: {id: {_eq: $id}},
    _set: {
      name: $name,
      points: $points,
      editor_id: $editor_id
    }
  ) {
    returning {
      id
    }
  }
}
