mutation updateJobs (
  $id: Int!,
  $name: String!,
  $points: Int!
) {
  update_jobs(
    where: {id: {_eq: $id}},
    _set: {
      name: $name,
      points: $points
    }
  ) {
    returning {
      id
    }
  }
}
