query volunteerEdit ($id: Int!, $tenant_id: Int!) {
  volunteers_by_pk(id: $id) {
    id
    joined_at
    first_name
    last_name
    email
    phone
    street
    city
    notes
    enrollees (where: {enrollment: {_and: [
      {start_date: {_lte: "now"}},
      {end_date: {_gte: "now"}},
      {membership: {deleted_at: {_is_null: true}}}
    ]}}) {
      enrollment {
        start_date
        end_date
        membership {
          id
          name
        }
      }
    }
  }
  awards (where: {volunteer_id: {_eq: $id}}) {
    awarded_at
    level {
      id
      name
    }
  }
  levels (
    where: {_and: [
      {deleted_at: {_is_null: true}},
      {tenant_id: {_eq: $tenant_id}}
    ]},
    order_by: {points: asc}
  ) {
    id
    name
    points
  }
  volunteer_shows_aggregate (where: {volunteer_id: {_eq: $id}}) {
    aggregate {
      sum {
        points
      }
    }
  }
}
