query volunteerEligible (
  $tenant_id: Int!,
  $offset: Int!,
  $limit: Int!,
  $sort: [volunteer_eligible_order_by!]
) {
  volunteer_eligible (
    where: {tenant_id: {_eq: $tenant_id}},
    order_by: $sort,
    limit: $limit,
    offset: $offset
  ) {
    id
    first_name
    last_name
    points
    shows
    enrollment {
      membership {
        name
      }
    }
    awards (
      order_by: {level: {points: desc}},
      limit: 1
    ) {
      level {
        name
        color
      }
    }
  }
}
