query volunteerFind ($id: Int!) {
  volunteers_by_pk(id: $id) {
    id
    joined_at
    first_name
    last_name
    volunteer_shows (order_by: {show: {occurred_at: desc}}) {
      points
      show {
        id
        name
        occurred_at
        positions (where: {volunteer_id: {_eq: $id}}) {
          points
          job {
            id
            name
            points
          }
        }
      }
    }
    awards {
      awarded_at
      level {
        name
        color
      }
    }
  }
}
