query myPost (
  $user_id: Int!,
  $now: timestamptz!
) {
  posts(
    where: {_and: [
      {user_id: {_eq: $user_id}},
      {expire_at: {_gt: $now}},
    ]},
    order_by: {created_at: desc},
    limit: 1
  ) {
    id
  }
}
