mutation updatePost (
    $id: Int!,
    $status: post_statuses_enum!
  ) {
  update_posts(
    where: {id: {_eq: $id}},
    _set: {
      status: $status
    },
  ) {
    returning {
      id
    }
  }
}
