query userCurrent ($authId: String!) {
  users(where: {auth_id: {_eq: $authId}}) {
    id
    auth_id
    name
    nickname
    email
    picture
    tenant {
      id
      name
    }
    tenants {
      id
      name
    }
  }
}
