query userCurrent ($id: Int!) {
  users_by_pk(id: $id) {
    id
    auth_id
    name
    nickname
    email
    picture
    first_name
    last_name
    tenant {
      id
      short_name
      name
      max_points_per_show
    }
    tenants {
      id
      name
    }
  }
}
