mutation userUpdate (
  $id: Int!,
  $first_name: String,
  $last_name: String,
) {
  update_users (
    where: {id: {_eq: $id}},
    _set: {
      first_name: $first_name,
      last_name: $last_name,
    },
  ) {
    returning {
      id
      name
    }
  }
}
