query levelList (
  $tenant_id: Int!
) {
  levels (
    where: {_and: [
      {tenant_id: {_eq: $tenant_id}},
      {deleted_at: {_is_null: true}}
    ]},
    order_by: {points: asc}
  ) {
    id
    name
    points
    color
  }
}
